### ISSUE TITLE
undefined refs when building xpload 0.8.0

### ISSUE THREAD

**Issue by pinkenburg** [BNLNPPS/xpload#29]
I am using this cmake to configure the build:
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/xpload-0.8.0 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SKIP_INSTALL_RPATH=ON -DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=Y -DBUILD_STATIC_LIBS=N ../

[phnxbld@cvmfswrite02 build]$ cmake --version
cmake version 3.22.2

make fails with:
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'

here is the complete make output:
[phnxbld@cvmfswrite02 build]$ make >& make.log
[phnxbld@cvmfswrite02 build]$ cat make.log 
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -S/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0 -B/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build --check-build-system CMakeFiles/Makefile.cmake 0
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_progress_start /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/CMakeFiles /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make  -f src/CMakeFiles/xpload.dir/build.make src/CMakeFiles/xpload.dir/depend
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_depends "Unix Makefiles" /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0 /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/src /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src/CMakeFiles/xpload.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make  -f src/CMakeFiles/xpload.dir/build.make src/CMakeFiles/xpload.dir/build
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
[ 12%] Building CXX object src/CMakeFiles/xpload.dir/configurator.cpp.o
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/gcc/8.3.0.1-0a5ad/x86_64-centos7/bin/g++ -Dxpload_EXPORTS -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/include -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/contrib -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/src -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src -O2 -g -DNDEBUG -fPIC -std=c++17 -MD -MT src/CMakeFiles/xpload.dir/configurator.cpp.o -MF CMakeFiles/xpload.dir/configurator.cpp.o.d -o CMakeFiles/xpload.dir/configurator.cpp.o -c /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/src/configurator.cpp
[ 25%] Building CXX object src/CMakeFiles/xpload.dir/fetch.cpp.o
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/gcc/8.3.0.1-0a5ad/x86_64-centos7/bin/g++ -Dxpload_EXPORTS -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/include -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/contrib -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/src -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src -O2 -g -DNDEBUG -fPIC -std=c++17 -MD -MT src/CMakeFiles/xpload.dir/fetch.cpp.o -MF CMakeFiles/xpload.dir/fetch.cpp.o.d -o CMakeFiles/xpload.dir/fetch.cpp.o -c /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/src/fetch.cpp
[ 37%] Linking CXX shared library libxpload.so
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_link_script CMakeFiles/xpload.dir/link.txt --verbose=1
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/gcc/8.3.0.1-0a5ad/x86_64-centos7/bin/g++ -fPIC -O2 -g -DNDEBUG -shared -Wl,-soname,libxpload.so.0.8.0 -o libxpload.so.0.8.0 CMakeFiles/xpload.dir/configurator.cpp.o CMakeFiles/xpload.dir/fetch.cpp.o  /usr/lib64/libcurl.so 
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/src && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_symlink_library libxpload.so.0.8.0 libxpload.so.0.8.0 libxpload.so
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
[ 37%] Built target xpload
make  -f tools/CMakeFiles/xpl.dir/build.make tools/CMakeFiles/xpl.dir/depend
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_depends "Unix Makefiles" /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0 /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/tools /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/CMakeFiles/xpl.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make  -f tools/CMakeFiles/xpl.dir/build.make tools/CMakeFiles/xpl.dir/build
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
[ 50%] Generating xpl
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/bin/python3.8 -m venv venv && source venv/bin/activate && python -m pip install --upgrade pip && python -m pip install pyinstaller -r requirements.txt && pyinstaller --onefile -n xpl --distpath . xpload.py && deactivate
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-22.0.4
Collecting pyinstaller
  Using cached pyinstaller-5.0-py3-none-manylinux2014_x86_64.whl (1.5 MB)
Collecting attrs==21.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.8
  Using cached charset_normalizer-2.0.8-py3-none-any.whl (39 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting jsonschema==4.2.1
  Using cached jsonschema-4.2.1-py3-none-any.whl (69 kB)
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pyrsistent==0.18.0
  Using cached pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl (118 kB)
Collecting pytest==7.1.1
  Using cached pytest-7.1.1-py3-none-any.whl (297 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting urllib3==1.26.7
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting importlib-resources>=1.4.0
  Using cached importlib_resources-5.7.1-py3-none-any.whl (28 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting altgraph
  Using cached altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from pyinstaller) (41.2.0)
Collecting pyinstaller-hooks-contrib>=2020.6
  Using cached pyinstaller_hooks_contrib-2022.4-py2.py3-none-any.whl (229 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Using legacy 'setup.py install' for pathlib, since package 'wheel' is not installed.
Installing collected packages: pathlib, iniconfig, certifi, altgraph, zipp, urllib3, tomli, pyrsistent, pyparsing, pyinstaller-hooks-contrib, py, pluggy, idna, charset-normalizer, attrs, requests, pyinstaller, packaging, importlib-resources, pytest, jsonschema
  Running setup.py install for pathlib: started
  Running setup.py install for pathlib: finished with status 'done'
Successfully installed altgraph-0.17.2 attrs-21.2.0 certifi-2021.10.8 charset-normalizer-2.0.8 idna-3.3 importlib-resources-5.7.1 iniconfig-1.1.1 jsonschema-4.2.1 packaging-21.3 pathlib-1.0.1 pluggy-1.0.0 py-1.11.0 pyinstaller-5.0 pyinstaller-hooks-contrib-2022.4 pyparsing-3.0.8 pyrsistent-0.18.0 pytest-7.1.1 requests-2.26.0 tomli-2.0.1 urllib3-1.26.7 zipp-3.8.0
75 INFO: PyInstaller: 5.0
75 INFO: Python: 3.8.0
77 INFO: Platform: Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-glibc2.2.5
78 INFO: wrote /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/xpl.spec
81 INFO: UPX is not available.
83 INFO: Extending PYTHONPATH with paths
['/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools']
278 INFO: checking Analysis
278 INFO: Building Analysis because Analysis-00.toc is non existent
278 INFO: Initializing module dependency graph...
281 INFO: Caching module graph hooks...
290 INFO: Analyzing base_library.zip ...
3826 INFO: Caching module dependency graph...
3964 INFO: running Analysis Analysis-00.toc
4005 INFO: Analyzing /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/xpload.py
4842 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
5290 INFO: Processing module hooks...
5291 INFO: Loading module hook 'hook-certifi.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5295 INFO: Loading module hook 'hook-jsonschema.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5310 INFO: Loading module hook 'hook-difflib.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5311 INFO: Loading module hook 'hook-encodings.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5371 INFO: Loading module hook 'hook-heapq.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5373 INFO: Loading module hook 'hook-importlib_resources.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5374 WARNING: Hidden import "importlib_resources.trees" not found!
5375 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5375 INFO: Import to be excluded not found: 'test'
5375 INFO: Loading module hook 'hook-pickle.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5376 INFO: Loading module hook 'hook-xml.py' from '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5447 INFO: Looking for ctypes DLLs
5453 INFO: Analyzing run-time hooks ...
5456 INFO: Including run-time hook '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
5457 INFO: Including run-time hook '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
5459 INFO: Including run-time hook '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
5462 INFO: Including run-time hook '/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
5468 INFO: Looking for dynamic libraries
6499 INFO: Looking for eggs
6500 INFO: Using Python library /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/lib/libpython3.8.so.1.0
6507 INFO: Warnings written to /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/build/xpl/warn-xpl.txt
6534 INFO: Graph cross-reference written to /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/build/xpl/xref-xpl.html
6568 INFO: checking PYZ
6569 INFO: Building PYZ because PYZ-00.toc is non existent
6569 INFO: Building PYZ (ZlibArchive) /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/build/xpl/PYZ-00.pyz
7033 INFO: Building PYZ (ZlibArchive) /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/build/xpl/PYZ-00.pyz completed successfully.
7043 INFO: checking PKG
7043 INFO: Building PKG because PKG-00.toc is non existent
7043 INFO: Building PKG (CArchive) xpl.pkg
17208 INFO: Building PKG (CArchive) xpl.pkg completed successfully.
17212 INFO: Bootloader /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/tools/venv/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
17212 INFO: checking EXE
17212 INFO: Building EXE because EXE-00.toc is non existent
17212 INFO: Building EXE from EXE-00.toc
17212 INFO: Copying bootloader EXE to ./xpl
17213 INFO: Appending PKG archive to custom ELF section in EXE
17318 INFO: Building EXE from EXE-00.toc completed successfully.
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
[ 50%] Built target xpl
make  -f test/CMakeFiles/test_xpload.dir/build.make test/CMakeFiles/test_xpload.dir/depend
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_depends "Unix Makefiles" /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0 /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/test /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/test /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/test/CMakeFiles/test_xpload.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make  -f test/CMakeFiles/test_xpload.dir/build.make test/CMakeFiles/test_xpload.dir/build
make[2]: Entering directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
[ 62%] Building CXX object test/CMakeFiles/test_xpload.dir/test_xpload.cpp.o
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/test && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/gcc/8.3.0.1-0a5ad/x86_64-centos7/bin/g++  -I/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/include -O2 -g -DNDEBUG -std=c++17 -MD -MT test/CMakeFiles/test_xpload.dir/test_xpload.cpp.o -MF CMakeFiles/test_xpload.dir/test_xpload.cpp.o.d -o CMakeFiles/test_xpload.dir/test_xpload.cpp.o -c /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/test/test_xpload.cpp
[ 75%] Linking CXX executable test_xpload
cd /gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build/test && /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/utils/stow/cmake-3.22.2/bin/cmake -E cmake_link_script CMakeFiles/test_xpload.dir/link.txt --verbose=1
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/gcc/8.3.0.1-0a5ad/x86_64-centos7/bin/g++ -O2 -g -DNDEBUG CMakeFiles/test_xpload.dir/test_xpload.cpp.o -o test_xpload  ../src/libxpload.so.0.8.0 /usr/lib64/libcurl.so 
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
../src/libxpload.so.0.8.0: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_xpload] Error 1
make[2]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make[1]: *** [test/CMakeFiles/test_xpload.dir/all] Error 2
make[1]: Leaving directory `/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/xpload-0.8.0/build'
make: *** [all] Error 2

**Comment by plexoos** [comment]
I believe your compiler (gcc 8.3) does not have complete or stable implementation of C++17 and therefore 'stdc++fs' has to be linked explicitly. This is fixed in [0.8.1](https://github.com/BNLNPPS/xpload/releases/tag/v0.8.1)

**Comment by plexoos** [comment]
Fixed by #26
